### PR TITLE
Add Bedrock Marketing Agent example

### PR DESCRIPTION
**Pull request by lubao**
*Issue #, if available:*

*Description of changes:*
The PR will add a use case example for bedrock marketing agent.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by rsgrewal-aws — CHANGES_REQUESTED** [review]
we need to remove the DB files - the repo is gettting too large and this would not be the plce to host them

**Comment by lubao** [comment]
Thanks for reviewing the PR.
Since the agent requires those sample datasets, do you have any suggestions on how to host the dataset properly?

**Comment by lubao** [comment]
remove db and image file to reduce the size.

**Comment by lubao** [comment]
Remove DB and Image file to reduce the size.

**Comment by lubao** [comment]
Pass bandit and cfn_nag security check

**Review by mttanke — APPROVED** [review]

**Pull request closed without merging**
