### PR TITLE
Added CrewAI notebook w Bedrock KB

### PR DESCRIPTION
**Pull request by claumazz**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rsgrewal-aws** [comment]
can you add the actual jupyter file

**Review by rsgrewal-aws — APPROVED** [review]
approved

**Comment by arnabaws15** [comment]
I got an error today for using memory when I chose embedder = aws_bedrock

`Exception: Unsupported embedding provider: aws_bedrock, supported providers: [openai, azure, ollama, vertexai, google, cohere, huggingface]`

Problematic code block:
```
# Enabling Memory in the Agent
crew_with_memory = Crew(
    agents=[travel_agent],
    tasks=[task],
    verbose=True,
    memory=True,  # Enable memory
    embedder={
        "provider": "aws_bedrock",
        "config": {
            "model": "amazon.titan-embed-text-v2:0",  # Embedding model for memory
            "vector_dimension": 1024
        }
    },
    
)
```

**Comment by claumazz** [comment]
@arnabaws15 which version of crewai and crewai tools are you using? Notebook is using crewai v 0.70.1 and crewai-tools 0.12.1

**Comment by arnabaws15** [comment]
Thanks. I was able to resolve the problem using the versions you listed.
I think it would be best to add the versions like this in the notebook?
`!pip install crewai==0.70.1 crewai_tools==0.12.1`

BTW any idea why Crew's [memory documentation](https://docs.crewai.com/concepts/memory) page doesn't have a listing for AWS Bedrock and Titan Embedding model?

**Comment by claumazz** [comment]
true, I can add a line stating the package versions. Reg documentation, thats something I've noticed with Crew. There is little to no documentation or code samples using Bedrock. What is the processes of engaging with the folks there to correct that?

**Comment by rsgrewal-aws** [comment]
@claumazz and @arnabaws15   we are working on that documentation changes. For this notebook - could we add the versions to the notebook and create a PR

**Comment by arnabaws15** [comment]
@rsgrewal-aws Done: https://github.com/aws-samples/amazon-bedrock-samples/pull/376

**Comment by rsgrewal-aws** [comment]
perfect merged it

**Pull request merged**
